[tool.black]
line-length = 79

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=modern --cov-fail-under=100 --cov-report=term-missing"
testpaths = ["tests"]
asyncio_mode = "strict"
